POST http://localhost:3000/members
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com"
}

###

GET http://localhost:3000/members

###

GET http://localhost:3000/members/{id}

###

POST http://localhost:3000/clubs
Content-Type: application/json

{
    "name": "Updated Club Name"
}

###

GET http://localhost:3000/clubs/{id}

###

GET http://localhost:3000/clubs